print('Enter a number to make a numeric table of his')
number = int(input('Number: '))
def putline ():
    return print('-'*11)
putline()
print(f'{number} x  1 = {number*1}')
print(f'{number} x  2 = {number*2}')
print('{} x  3 = {}'.format(number,number*3))
print(f'{number} x  4 = {number*4}')
print(f'{number} x  5 = {number*5}')
print(number,'x  6 =',(number*6))
print(f'{number} x  7 = {number*7}')
print(f'{number} x  8 = {number*8}')
print(f'{number} x  9 = {number*9}')
print(f'{number} x 10 = {number*10}')
print('-'*11)
