print('Digite algo e verificaremos o que digitou')
algo = input('Digite algo: ')
tipo = type(algo)
print(f'é do tipo {tipo}')
print('é número? ',algo.isnumeric())
print('somente letras? ',algo.isalpha())
print('contém número e/ou letras? ',algo.isalnum())
print('são maiúsculas? ',algo.isupper())
print('são minúsculas? ',algo.islower())
print('são digítos? ',algo.isdigit())
print('Contém somente espaços? ',algo.isspace())
print('é imprimivel? ',algo.isprintable())
print('é possível usar esse nome como variável? ',algo.isidentifier())
print('primeira letra de cada palavra é maiúscula? ',algo.istitle())
